<html>
<head>
    <title>Contact via le mini-site Ecommercesolidaire</title>
</head>
<body>
<p>{{PRENOM}} {{NOM}} vous a contacté via notre mini-site Ecommercesolidaire</p>
<table>
    <tr>
        <td>Son nom</td>
        <td>{{NOM}}</td>
    </tr>
    <tr>
        <td>Son prénom</td>
        <td>{{PRENOM}}</td>
    </tr>
    <tr>
        <td>Téléphone</td>
        <td>{{TELEPHONE}}</td>
    </tr>
    <tr>
        <td>Email</td>
        <td>{{EMAIL}}</td>
    </tr>
    <tr>
        <td>Société</td>
        <td>{{SOCIETE}}</td>
    </tr>
    <tr>
        <td>Siren</td>
        <td>{{SIREN}}</td>
    </tr>
    <tr>
        <td>Salaries</td>
        <td>{{SALARIES}}</td>
    </tr>
    <tr>
        <td>Statut</td>
        <td>{{STATUT}}</td>
    </tr>
    <tr>
        <td>Adresse</td>
        <td>{{ADRESSE}}</td>
    </tr>
    <tr>
        <td>Code Postal</td>
        <td>{{CP}}</td>
    </tr>
    <tr>
        <td>Ville</td>
        <td>{{VILLE}}</td>
    </tr>
    <tr>
        <td>Pays</td>
        <td>{{PAYS}}</td>
    </tr>
    <tr>
        <td>Commentaires</td>
        <td>{{COMMENTAIRES}}</td>
    </tr>
</table>
</body>
</html>